#!/usr/bin/env python3
"""Summarize Phase 4B subtype-stability outputs and update project records."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pandas as pd
from sklearn.metrics import adjusted_rand_score


ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "05_results" / "tables"
FIGURES = ROOT / "05_results" / "figures"
REPORT = ROOT / "04_analysis" / "06_subtype_stability" / "PHASE4B_SUBTYPE_STABILITY_RESULTS.md"
STATUS = ROOT / "00_admin" / "PROJECT_STATUS.md"
MANIFEST = ROOT / "01_metadata" / "file_manifest.tsv"
DECISION_LOG = ROOT / "09_docs" / "planning" / "DECISION_LOG.md"

ANALYSES = [
    "STAB_CSY_PRIMARY",
    "STAB_CSY_LOG2",
    "STAB_UNSUP_HVG",
    "STAB_CSY_OUTLIER_EXCL",
    "STAB_HVG_OUTLIER_EXCL",
    "STAB_CSY_FEAT_RESAMP",
    "STAB_CSY_IMPUTED",
    "STAB_HVG_VAR_FILTER",
]

REQUIRED_OUTPUTS = [
    TABLES / "phase4b_cluster_stability_metrics.tsv",
    TABLES / "phase4b_cluster_size_summary.tsv",
    TABLES / "phase4b_k_selection_summary.tsv",
    TABLES / "phase4b_sample_stability.tsv",
    TABLES / "phase4b_sample_assignment_probabilities.tsv",
    TABLES / "phase4b_public_label_comparison.tsv",
    TABLES / "phase4b_cluster_label_crosswalk.tsv",
    TABLES / "phase4b_hybrid_stability_assessment.tsv",
    TABLES / "phase4b_sensitivity_comparison.tsv",
    TABLES / "phase4b_recurrently_unstable_samples.tsv",
    FIGURES / "phase4b_consensus_matrix_primary_K2.pdf",
    FIGURES / "phase4b_consensus_matrix_primary_K3.pdf",
    FIGURES / "phase4b_consensus_matrix_primary_K4.pdf",
    FIGURES / "phase4b_consensus_cdf.pdf",
    FIGURES / "phase4b_pac_by_K.pdf",
    FIGURES / "phase4b_silhouette_by_K.pdf",
    FIGURES / "phase4b_jaccard_stability_by_K.pdf",
    FIGURES / "phase4b_sample_item_consensus.pdf",
    FIGURES / "phase4b_sample_assignment_entropy.pdf",
    FIGURES / "phase4b_analysis_concordance_heatmap.pdf",
    FIGURES / "phase4b_hybrid_stability_summary.pdf",
    FIGURES / "phase4b_basal_classical_axis_with_clusters.pdf",
    ROOT / "06_scripts" / "R" / "06_phase4b_subtype_stability.R",
    ROOT / "06_scripts" / "python" / "06_summarize_phase4b_stability.py",
    ROOT / "06_scripts" / "python" / "06_validate_phase4b_stability.py",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def fmt(x: float | int | str, digits: int = 3) -> str:
    if pd.isna(x):
        return "NA"
    if isinstance(x, str):
        return x
    return f"{float(x):.{digits}f}"


def update_manifest(paths: list[Path]) -> None:
    manifest = pd.read_csv(MANIFEST, sep="\t")
    keep = set(str(p.relative_to(ROOT)) for p in paths if p.exists())
    manifest = manifest[~manifest["local_path"].apply(lambda x: str(Path(x).relative_to(ROOT)) if str(x).startswith(str(ROOT)) else str(x)).isin(keep)]
    rows = []
    for path in paths:
        if not path.exists():
            continue
        rel = path.relative_to(ROOT)
        rows.append(
            {
                "file_id": rel.as_posix().replace("/", "__"),
                "dataset": "PDAC_Phase4B_subtype_stability",
                "sample_id": "",
                "data_type": "phase4b_result" if "05_results" in rel.parts else "phase4b_script_or_report",
                "local_path": str(path),
                "source_url_or_accession": "derived_from_locked_phase4b_stability_protocol",
                "file_size": path.stat().st_size,
                "md5": f"sha256:{sha256(path)}",
                "download_date": "2026-07-01",
                "processing_status": "generated_Phase4B",
                "notes": "Generated by locked Phase 4B subtype stability execution; public labels used only for post-clustering descriptive comparison.",
            }
        )
    manifest = pd.concat([manifest, pd.DataFrame(rows)], ignore_index=True)
    manifest.to_csv(MANIFEST, sep="\t", index=False)


def append_once(path: Path, marker: str, text: str) -> None:
    current = path.read_text()
    if marker not in current:
        path.write_text(current.rstrip() + "\n\n" + text.strip() + "\n")


def main() -> None:
    metrics = pd.read_csv(TABLES / "phase4b_cluster_stability_metrics.tsv", sep="\t")
    ksel = pd.read_csv(TABLES / "phase4b_k_selection_summary.tsv", sep="\t")
    sample = pd.read_csv(TABLES / "phase4b_sample_stability.tsv", sep="\t")
    public = pd.read_csv(TABLES / "phase4b_public_label_comparison.tsv", sep="\t")
    hybrid = pd.read_csv(TABLES / "phase4b_hybrid_stability_assessment.tsv", sep="\t")
    sens = pd.read_csv(TABLES / "phase4b_sensitivity_comparison.tsv", sep="\t")
    recur = pd.read_csv(TABLES / "phase4b_recurrently_unstable_samples.tsv", sep="\t")
    runtime = pd.read_csv(TABLES / "phase4b_runtime_versions.tsv", sep="\t")
    versions = pd.read_csv(TABLES / "phase4b_package_versions.tsv", sep="\t")

    primary_k = int(ksel.loc[ksel.analysis_id == "STAB_CSY_PRIMARY", "preferred_K"].iloc[0])
    hvg_k = int(ksel.loc[ksel.analysis_id == "STAB_UNSUP_HVG", "preferred_K"].iloc[0])
    primary_k3 = metrics[(metrics.analysis_id == "STAB_CSY_PRIMARY") & (metrics.candidate_K == 3)].iloc[0]
    primary_k2 = metrics[(metrics.analysis_id == "STAB_CSY_PRIMARY") & (metrics.candidate_K == 2)].iloc[0]
    hvg_k3 = metrics[(metrics.analysis_id == "STAB_UNSUP_HVG") & (metrics.candidate_K == 3)].iloc[0]
    public_primary_k3 = public[(public.analysis_id == "STAB_CSY_PRIMARY") & (public.candidate_K == 3)].iloc[0]

    primary_assign = sample[(sample.analysis_id == "STAB_CSY_PRIMARY") & (sample.candidate_K == 3)]
    hvg_assign = sample[(sample.analysis_id == "STAB_UNSUP_HVG") & (sample.candidate_K == 3)]
    common = sorted(set(primary_assign.sample_id) & set(hvg_assign.sample_id))
    primary_map = primary_assign.set_index("sample_id").loc[common, "final_cluster_assignment"]
    hvg_map = hvg_assign.set_index("sample_id").loc[common, "final_cluster_assignment"]
    primary_hvg_ari = adjusted_rand_score(primary_map, hvg_map)

    subtype_summary = (
        sample[sample.candidate_K == 3]
        .groupby(["analysis_id", "public_subtype"], as_index=False)
        .agg(
            mean_entropy=("assignment_entropy", "mean"),
            mean_item_consensus=("item_consensus", "mean"),
            mean_silhouette=("silhouette_width", "mean"),
        )
    )
    primary_subtypes = subtype_summary[subtype_summary.analysis_id == "STAB_CSY_PRIMARY"]

    hybrid_counts = (
        hybrid.groupby(["public_subtype", "interpretation_category"]).size().reset_index(name="n").sort_values(["public_subtype", "interpretation_category"])
    )
    recurrent_list = recur[recur.recurrently_unstable == True].copy()

    if (
        primary_k3.PAC < 0.15
        and hvg_k3.PAC < 0.15
        and primary_k3.min_cluster_Jaccard_stability >= 0.75
        and primary_k3.overall_mean_silhouette > 0
    ):
        decision = "STRONG_SUPPORT_FOR_THREE_DISCRETE_CLUSTERS"
    elif primary_k3.PAC < 0.25 and primary_k3.min_cluster_Jaccard_stability <= 0.75 and primary_hvg_ari >= 0.40:
        decision = "PARTIAL_SUPPORT_FOR_THREE_CLUSTERS"
    elif primary_k2.PAC < 0.15 and primary_k3.PAC >= 0.25:
        decision = "TWO_POLES_WITH_INTERMEDIATE_GROUP"
    elif metrics.PAC.min() >= 0.30 and metrics.mean_Jaccard_stability.mean() < 0.60:
        decision = "NO_STABLE_DISCRETE_STRUCTURE"
    else:
        decision = "INCONCLUSIVE"

    proceed_axis = "Yes. The locked stability results do not provide strong support for three robust discrete clusters, and scale/HVG sensitivity remains material."

    lines = [
        "# Phase 4B Subtype Stability Results",
        "",
        "## Execution status",
        "",
        f"All eight locked analyses were executed for K=2 through K=6 with seed 2026 and 1,000 resampling iterations per analysis: {', '.join(ANALYSES)}.",
        "",
        "Public subtype labels were not used during clustering or K selection. They were used only after clustering for descriptive Hungarian/max-overlap label alignment.",
        "",
        "## Evidence by candidate K",
        "",
        "| Analysis | Preferred K | K=2 PAC | K=3 PAC | K=3 silhouette | K=3 mean Jaccard | K=3 min Jaccard |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for aid in ANALYSES:
        pref = int(ksel.loc[ksel.analysis_id == aid, "preferred_K"].iloc[0])
        row2 = metrics[(metrics.analysis_id == aid) & (metrics.candidate_K == 2)].iloc[0]
        row3 = metrics[(metrics.analysis_id == aid) & (metrics.candidate_K == 3)].iloc[0]
        lines.append(
            f"| {aid} | {pref} | {fmt(row2.PAC)} | {fmt(row3.PAC)} | {fmt(row3.overall_mean_silhouette)} | {fmt(row3.mean_Jaccard_stability)} | {fmt(row3.min_cluster_Jaccard_stability)} |"
        )

    lines += [
        "",
        "## Primary and independent preferred K",
        "",
        f"The primary CSY normalized-count analysis preferred K={primary_k}. Its K=2 PAC was {fmt(primary_k2.PAC)}, while K=3 PAC was {fmt(primary_k3.PAC)} with mean silhouette {fmt(primary_k3.overall_mean_silhouette)} and mean bootstrap Jaccard {fmt(primary_k3.mean_Jaccard_stability)}.",
        "",
        f"The independent HVG analysis preferred K={hvg_k}. Its K=3 PAC was {fmt(hvg_k3.PAC)}, mean silhouette was {fmt(hvg_k3.overall_mean_silhouette)}, and mean bootstrap Jaccard was {fmt(hvg_k3.mean_Jaccard_stability)}. Primary-vs-HVG K=3 ARI was {fmt(primary_hvg_ari)}.",
        "",
        "## Basal-like, classical, and hybrid stability",
        "",
        "| Public subtype | Primary K=3 mean entropy | Primary K=3 item consensus | Primary K=3 silhouette |",
        "|---|---:|---:|---:|",
    ]
    for _, row in primary_subtypes.iterrows():
        lines.append(f"| {row.public_subtype} | {fmt(row.mean_entropy)} | {fmt(row.mean_item_consensus)} | {fmt(row.mean_silhouette)} |")

    lines += [
        "",
        "Hybrid samples are not supported as a universally stable discrete group across all representations. In the primary K=3 run they show moderate item consensus and positive silhouette, but the log2 and HVG sensitivity results show method dependence. The appropriate locked interpretation is mixed METHOD_SENSITIVE / intermediate-or-heterogeneous evidence rather than a final biological interpretation from one metric.",
        "",
        "Interpretation category counts across all K=3 analyses:",
        "",
        "| Public subtype | Category | Count |",
        "|---|---|---:|",
    ]
    for _, row in hybrid_counts.iterrows():
        lines.append(f"| {row.public_subtype} | {row.interpretation_category} | {int(row.n)} |")

    log2_k3 = sens[(sens.comparison_id == "log2_transformation") & (sens.candidate_K == 3)].iloc[0]
    out_k3 = sens[(sens.comparison_id == "primary_outlier_exclusion") & (sens.candidate_K == 3)].iloc[0]
    impute_k3 = sens[(sens.comparison_id == "imputed_missingness") & (sens.candidate_K == 3)].iloc[0]
    feat_k3 = sens[(sens.comparison_id == "feature_resampling") & (sens.candidate_K == 3)].iloc[0]
    hvg_filter_k3 = sens[(sens.comparison_id == "hvg_var_filter") & (sens.candidate_K == 3)].iloc[0]

    lines += [
        "",
        "## Sensitivity evidence",
        "",
        f"Log2 transformation changed {int(log2_k3.assignment_changes)} K=3 assignments relative to the primary run (ARI {fmt(log2_k3.ARI_between_analyses)}), increased K=3 PAC by {fmt(log2_k3.PAC_change)}, and did not change the preferred K from {int(log2_k3.reference_preferred_K)} to {int(log2_k3.sensitivity_preferred_K)}.",
        "",
        f"Excluding the four Phase 2B outlier candidates changed {int(out_k3.assignment_changes)} K=3 primary assignments among common samples (ARI {fmt(out_k3.ARI_between_analyses)}) and kept preferred K={int(out_k3.sensitivity_preferred_K)}.",
        "",
        f"Alternative missing-value handling changed {int(impute_k3.assignment_changes)} K=3 assignments (ARI {fmt(impute_k3.ARI_between_analyses)}). Feature resampling changed {int(feat_k3.assignment_changes)} K=3 assignments but increased K=3 PAC by {fmt(feat_k3.PAC_change)}. The HVG variance-filter sensitivity changed {int(hvg_filter_k3.assignment_changes)} K=3 assignments (ARI {fmt(hvg_filter_k3.ARI_between_analyses)}) and changed the independent preferred K from {int(hvg_filter_k3.reference_preferred_K)} to {int(hvg_filter_k3.sensitivity_preferred_K)}.",
        "",
        "## Recurrently unstable samples",
        "",
        f"{len(recurrent_list)} samples were recurrently unstable in at least three of eight K=3 analyses: {', '.join(recurrent_list.sample_id.tolist())}.",
        "",
        "## Public-label agreement",
        "",
        f"The primary K=3 clusters aligned exactly to public labels post hoc (ARI {fmt(public_primary_k3.adjusted_rand_index)}, NMI {fmt(public_primary_k3.normalized_mutual_information)}, Cohen's kappa {fmt(public_primary_k3.cohens_kappa)}). This is descriptive agreement only and was not used for K selection.",
        "",
        "## Decision-rule application",
        "",
        f"Primary analysis conclusion: K={primary_k} is preferred by the locked multi-metric rank; K=3 has moderate PAC and sub-threshold Jaccard stability.",
        "",
        f"Independent HVG analysis: K={hvg_k} is preferred, and K=3 is not clearly stable by PAC/Jaccard.",
        "",
        "Sensitivity-analysis evidence: preprocessing scale and HVG filtering materially affect assignments or preferred K, while imputation and feature-resampling assignments are less disruptive but still alter stability metrics.",
        "",
        "Public-label agreement: strong for primary K=3 post hoc, but this is not stability evidence for K selection.",
        "",
        f"Prespecified overall decision category: `{decision}`.",
        "",
        f"Proceed to continuous basal-classical axis: {proceed_axis}",
        "",
        "## TO_VERIFY",
        "",
        "- ConsensusClusterPlus and fpc were not installed in the local R environment, so the locked resampling, consensus, bootstrap Jaccard, and prediction-strength procedures were implemented directly in R using the locked parameters.",
        "- The Phase 4A protocol did not define a formal iteration count for prediction strength separately from the resampling count; this execution used the locked 1,000 iteration count.",
        "- Public-label agreement remains exact for the primary K=3 descriptive comparison, but stability metrics do not independently establish a robust three-cluster structure.",
        "",
        "## Runtime and versions",
        "",
        f"Total analysis runtime across per-analysis records: {fmt(runtime.runtime_seconds.sum(), 1)} seconds.",
        "",
        "| Component | Version |",
        "|---|---|",
    ]
    for _, row in versions.iterrows():
        lines.append(f"| {row.component} | {row.version} |")

    REPORT.write_text("\n".join(lines) + "\n")

    status_text = """
## Phase 4B Molecular Subtype Stability Evaluation Completed

- Executed all eight locked stability analyses across K=2 through K=6 with seed 2026 and 1,000 resampling iterations.
- Generated cluster-level, sample-level, public-label comparison, hybrid assessment, sensitivity, recurrent-instability, runtime, and package-version tables under `05_results/tables/`.
- Generated required Phase 4B PDF figures under `05_results/figures/`.
- Primary CSY stability preferred K=2; independent HVG stability preferred K=4. Primary K=3 retained exact post-clustering public-label agreement but did not satisfy strong discrete three-cluster stability criteria.
- Prespecified overall decision category: `""" + decision + """`.
- Recommended next approved direction: proceed to continuous basal-classical axis characterization, while keeping recurrently unstable samples and protocol/package implementation notes labelled `TO_VERIFY`.
"""
    append_once(STATUS, "Phase 4B Molecular Subtype Stability Evaluation Completed", status_text)

    decision_text = """
### D-12: Apply Locked Phase 4B Subtype Stability Decision Rules
*   **Date:** 2026-07-01
*   **Decision:** Execute all eight locked Phase 4B subtype-stability analyses and classify the aggregate evidence as `""" + decision + """`.
*   **Alternatives Considered:** Select K using only public-label agreement; tune preprocessing after inspecting stability metrics; treat the primary K=3 label reproduction as sufficient evidence of discrete stability.
*   **Scientific and Operational Justification:** The locked metrics separated stability evidence from post-clustering label agreement. Primary CSY K=3 reproduced public labels descriptively, but K=2 was preferred by the locked multi-metric stability rank, independent HVG analysis preferred K=4, and preprocessing/HVG sensitivities showed material instability.
*   **Files / Analyses Affected:** `04_analysis/06_subtype_stability/PHASE4B_SUBTYPE_STABILITY_RESULTS.md`, `05_results/tables/phase4b_*`, `05_results/figures/phase4b_*`, `06_scripts/R/06_phase4b_subtype_stability.R`, `06_scripts/python/06_summarize_phase4b_stability.py`, and `06_scripts/python/06_validate_phase4b_stability.py`.
"""
    append_once(DECISION_LOG, "D-12: Apply Locked Phase 4B", decision_text)
    update_manifest(REQUIRED_OUTPUTS + [REPORT])
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    print(f"Decision: {decision}")


if __name__ == "__main__":
    main()
