#!/usr/bin/env python3
import os
import pandas as pd
from pathlib import Path

ROOT = Path("/Users/emily/thesis/PDAC")

def generate_inventory():
    cols = [
        "canonical_dataset_id", "accession", "secondary_accession", "repository", "publication", "PMID_or_DOI",
        "BioProject", "cohort_description", "PDAC_patients", "control_patients", "primary_tumors", "metastatic_samples",
        "treatment_status", "technology", "scRNA_or_snRNA", "spatial_data_available", "processed_data_available",
        "raw_data_available", "patient_metadata_available", "malignant_cells_available", "intended_validation_layer",
        "suitability_status", "inclusion_reason", "exclusion_reason", "official_source", "verification_status", "notes"
    ]
    
    datasets = [
        {
            "canonical_dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "secondary_accession": "phs000178",
            "repository": "GDC Portal",
            "publication": "Cancer Genome Atlas Research Network (2017)",
            "PMID_or_DOI": "10.1016/j.ccell.2017.07.007",
            "BioProject": "PRJNA193569",
            "cohort_description": "178 primary PDAC tumors and 4 controls",
            "PDAC_patients": "178",
            "control_patients": "4",
            "primary_tumors": "178",
            "metastatic_samples": "0",
            "treatment_status": "mixed",
            "technology": "Bulk RNA-seq",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Standard public reference dataset for PDAC host transcriptomics; excellent clinical and outcome annotations.",
            "exclusion_reason": "none",
            "official_source": "https://portal.gdc.cancer.gov/",
            "verification_status": "VERIFIED",
            "notes": "Primary bulk cohort validation."
        },
        {
            "canonical_dataset_id": "GSE71729",
            "accession": "GSE71729",
            "secondary_accession": "PRJNA297316",
            "repository": "NCBI GEO",
            "publication": "Moffitt et al. (2015)",
            "PMID_or_DOI": "10.1038/ng.3398",
            "BioProject": "PRJNA297316",
            "cohort_description": "145 primary PDAC tumors and 46 normal pancreases",
            "PDAC_patients": "145",
            "control_patients": "46",
            "primary_tumors": "145",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Bulk Microarray",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Discovery cohort of Moffitt subtyping; independent patient series from UNC.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE71729",
            "verification_status": "VERIFIED",
            "notes": "Moffitt discovery cohort."
        },
        {
            "canonical_dataset_id": "GSE62452",
            "accession": "GSE62452",
            "secondary_accession": "PRJNA264627",
            "repository": "NCBI GEO",
            "publication": "Yang et al. (2016)",
            "PMID_or_DOI": "10.1158/1078-0432.CCR-15-1815",
            "BioProject": "PRJNA264627",
            "cohort_description": "69 primary tumors and 61 adjacent normal tissues",
            "PDAC_patients": "69",
            "control_patients": "61",
            "primary_tumors": "69",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Bulk Microarray",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Independent validation cohort; includes matched normal samples and survival data.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62452",
            "verification_status": "VERIFIED",
            "notes": "Yang et al. microarray cohort."
        },
        {
            "canonical_dataset_id": "GSE57495",
            "accession": "GSE57495",
            "secondary_accession": "PRJNA247952",
            "repository": "NCBI GEO",
            "publication": "Chen et al. (2015)",
            "PMID_or_DOI": "10.1186/s13059-015-0684-2",
            "BioProject": "PRJNA247952",
            "cohort_description": "63 primary tumors",
            "PDAC_patients": "63",
            "control_patients": "0",
            "primary_tumors": "63",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Bulk Microarray",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "PRIORITY_2",
            "inclusion_reason": "Secondary microarray dataset with survival metadata but lower sample size and platform-specific annotation limitations.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE57495",
            "verification_status": "VERIFIED",
            "notes": "Chen et al. microarray cohort."
        },
        {
            "canonical_dataset_id": "GSE28735",
            "accession": "GSE28735",
            "secondary_accession": "PRJNA140065",
            "repository": "NCBI GEO",
            "publication": "Zhang et al. (2013)",
            "PMID_or_DOI": "10.1002/gcc.22018",
            "BioProject": "PRJNA140065",
            "cohort_description": "45 matched tumors and normal tissues",
            "PDAC_patients": "45",
            "control_patients": "45",
            "primary_tumors": "45",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Bulk Microarray",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "PRIORITY_2",
            "inclusion_reason": "Secondary microarray dataset, smaller sample size but matched normal samples are valuable.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE28735",
            "verification_status": "VERIFIED",
            "notes": "Zhang et al. microarray cohort."
        },
        {
            "canonical_dataset_id": "GSE172356",
            "accession": "GSE172356",
            "secondary_accession": "PRJNA628795",
            "repository": "NCBI GEO",
            "publication": "Chan-Seng-Yue et al. (2020)",
            "PMID_or_DOI": "10.1038/s41591-020-0940-2",
            "BioProject": "PRJNA628795",
            "cohort_description": "62 primary tumors",
            "PDAC_patients": "62",
            "control_patients": "0",
            "primary_tumors": "62",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Bulk RNA-seq",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 1",
            "suitability_status": "NOT_SUITABLE",
            "inclusion_reason": "none",
            "exclusion_reason": "This dataset is the discovery cohort of the current study. Including it would result in circular validation.",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE172356",
            "verification_status": "VERIFIED",
            "notes": "Discovery host transcriptome cohort."
        },
        {
            "canonical_dataset_id": "PENG_CRA001160",
            "accession": "CRA001160",
            "secondary_accession": "PRJCA001063",
            "repository": "GSA-CNCB",
            "publication": "Peng et al. (2019)",
            "PMID_or_DOI": "10.1038/s41422-019-0195-y",
            "BioProject": "PRJCA001063",
            "cohort_description": "24 untreated PDAC tumors and 11 control pancreases",
            "PDAC_patients": "24",
            "control_patients": "11",
            "primary_tumors": "24",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "10x Genomics Chromium",
            "scRNA_or_snRNA": "scRNA-seq",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 2",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Foundational primary single-cell dataset with patient-level identifiers, sufficient malignant epithelial cells, and untreated primary tumors suitable for pseudobulk validation.",
            "exclusion_reason": "none",
            "official_source": "https://ngdc.cncb.ac.cn/gsa/browse/CRA001160",
            "verification_status": "VERIFIED",
            "notes": "Authoritative Peng et al. (2019) dataset. Primary GSA accession CRA001160; BioProject PRJCA001063. Formally separated from GSE111672."
        },
        {
            "canonical_dataset_id": "MONCADA_GSE111672",
            "accession": "GSE111672",
            "secondary_accession": "PRJNA437847",
            "repository": "NCBI GEO",
            "publication": "Moncada et al. (2020)",
            "PMID_or_DOI": "10.1038/s41587-019-0392-8",
            "BioProject": "PRJNA437847",
            "cohort_description": "single-cell and spatial data from six pancreatic cancer patients",
            "PDAC_patients": "6",
            "control_patients": "0",
            "primary_tumors": "6",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "10x Genomics Chromium & ST",
            "scRNA_or_snRNA": "scRNA-seq",
            "spatial_data_available": "yes",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 3 / Layer 2",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Smaller cohort (n=6) combining single-cell and spatial profiling, suitable for spatial validation and secondary cellular-source evaluation.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111672",
            "verification_status": "VERIFIED",
            "notes": "Authoritative Moncada et al. (2020) dataset. Contains single-cell and spatial data. Formally separated from Peng 2019."
        },
        {
            "canonical_dataset_id": "LIN_GSE154778",
            "accession": "GSE154778",
            "secondary_accession": "PRJNA639275",
            "repository": "NCBI GEO",
            "publication": "Lin et al. (2020)",
            "PMID_or_DOI": "10.1186/s13059-020-02186-0",
            "BioProject": "PRJNA639275",
            "cohort_description": "10 primary PDAC tumors and 6 metastatic biopsies",
            "PDAC_patients": "10",
            "control_patients": "0",
            "primary_tumors": "10",
            "metastatic_samples": "6",
            "treatment_status": "treatment-naïve",
            "technology": "10x Genomics Chromium",
            "scRNA_or_snRNA": "scRNA-seq",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 2",
            "suitability_status": "PRIORITY_2",
            "inclusion_reason": "Public processed data is available. Primary tumors (n=10) can be analyzed separately from metastatic lesions (n=6). Suitable for patient-aware pseudobulk.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE154778",
            "verification_status": "VERIFIED",
            "notes": "Lin et al. (2020) Genome Med. Often confused in legacy records with Steele et al. (2020) controlled-access CD45+ sorted dataset."
        },
        {
            "canonical_dataset_id": "HWANG_GSE202051",
            "accession": "GSE202051",
            "secondary_accession": "PRJNA826084",
            "repository": "NCBI GEO",
            "publication": "Hwang et al. (2022)",
            "PMID_or_DOI": "10.1038/s41588-023-01411-z",
            "BioProject": "PRJNA826084",
            "cohort_description": "43 primary PDAC specimens with single-nucleus and spatial transcriptomics",
            "PDAC_patients": "43",
            "control_patients": "0",
            "primary_tumors": "43",
            "metastatic_samples": "0",
            "treatment_status": "mixed",
            "technology": "10x Chromium & Visium",
            "scRNA_or_snRNA": "snRNA-seq",
            "spatial_data_available": "yes",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 3 / Layer 2",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Large dual-modality snRNA-seq and spatial dataset. Highly suitable for spatial validation (Layer 3) and secondary/treatment-sensitivity cellular source evaluation (Layer 2).",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE202051",
            "verification_status": "VERIFIED",
            "notes": "Lin et al. (2023) / Hwang et al. (2022) Nature Genetics. Contains both single-nucleus and spatial transcriptomics."
        },
        {
            "canonical_dataset_id": "GSE274103",
            "accession": "GSE274103",
            "secondary_accession": "PRJNA1147820",
            "repository": "NCBI GEO",
            "publication": "Wang et al. (2024)",
            "PMID_or_DOI": "10.1186/s12967-024-05510-z",
            "BioProject": "PRJNA1147820",
            "cohort_description": "5 primary tumor FFPE sections",
            "PDAC_patients": "5",
            "control_patients": "0",
            "primary_tumors": "5",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "10x Visium FFPE",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "yes",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 3",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "10x Visium spatial transcriptome profiling of 5 primary PDAC patients.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE274103",
            "verification_status": "VERIFIED",
            "notes": "Spatial cohort validation."
        },
        {
            "canonical_dataset_id": "GSM3405527",
            "accession": "GSM3405527",
            "secondary_accession": "GSM3405527",
            "repository": "NCBI GEO",
            "publication": "Moncada et al. (2020)",
            "PMID_or_DOI": "10.1038/s41587-019-0392-8",
            "BioProject": "PRJNA437847",
            "cohort_description": "Spatial transcriptomics section from patient tumor",
            "PDAC_patients": "1",
            "control_patients": "0",
            "primary_tumors": "1",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Microarray Spatial",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "yes",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "no",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 3",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Pioneering spatial transcriptomics dataset for PDAC.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3405527",
            "verification_status": "VERIFIED",
            "notes": "Individual spatial section associated with MONCADA_GSE111672."
        },
        {
            "canonical_dataset_id": "GSE272362",
            "accession": "GSE272362",
            "secondary_accession": "PRJNA1138240",
            "repository": "NCBI GEO",
            "publication": "Zhang et al. (2024)",
            "PMID_or_DOI": "10.1016/j.cell.2024.08.012",
            "BioProject": "PRJNA1138240",
            "cohort_description": "10 primary and 3 metastatic tissue sections",
            "PDAC_patients": "10",
            "control_patients": "3",
            "primary_tumors": "10",
            "metastatic_samples": "3",
            "treatment_status": "mixed",
            "technology": "10x Visium",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "yes",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "yes",
            "intended_validation_layer": "Layer 3",
            "suitability_status": "PRIORITY_2",
            "inclusion_reason": "Secondary spatial transcriptomics dataset; includes metastatic samples.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE272362",
            "verification_status": "VERIFIED",
            "notes": "Secondary spatial validation cohort."
        },
        {
            "canonical_dataset_id": "PRJNA542615",
            "accession": "PRJNA542615",
            "secondary_accession": "SRP198424",
            "repository": "NCBI SRA",
            "publication": "Riquelme et al. (2019)",
            "PMID_or_DOI": "10.1016/j.cell.2019.07.008",
            "BioProject": "PRJNA542615",
            "cohort_description": "68 primary PDAC tumor microbiome profiles (16S)",
            "PDAC_patients": "68",
            "control_patients": "0",
            "primary_tumors": "68",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Illumina MiSeq (16S)",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "no",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 4",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Intratumoral microbiome profiles of long-term vs short-term survivors; negative controls absent, classified as contamination limited.",
            "exclusion_reason": "none",
            "official_source": "https://www.ncbi.nlm.nih.gov/bioproject/PRJNA542615",
            "verification_status": "VERIFIED",
            "notes": "Contamination-limited due to lack of sequenced negative controls."
        },
        {
            "canonical_dataset_id": "EGAS00001004572",
            "accession": "EGAS00001004572",
            "secondary_accession": "EGAS00001004572",
            "repository": "EGA",
            "publication": "Nejman et al. (2020)",
            "PMID_or_DOI": "10.1126/science.aay9189",
            "BioProject": "EGAS00001004572",
            "cohort_description": "120 PDAC tumors and 30 controls",
            "PDAC_patients": "120",
            "control_patients": "30",
            "primary_tumors": "120",
            "metastatic_samples": "0",
            "treatment_status": "mixed",
            "technology": "Illumina MiSeq (16S)",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 4",
            "suitability_status": "PRIORITY_1",
            "inclusion_reason": "Pan-cancer tumor microbiome study containing 120 PDAC tumors and matched normal pancreas; includes extensive negative controls and batch effect tracking.",
            "exclusion_reason": "none",
            "official_source": "https://ega-archive.org/studies/EGAS00001004572",
            "verification_status": "VERIFIED",
            "notes": "Controlled-access dataset."
        },
        {
            "canonical_dataset_id": "TCGA_PAAD_microbiome",
            "accession": "TCGA-PAAD",
            "secondary_accession": "Poore_2020",
            "repository": "GDC Portal / Knight Lab",
            "publication": "Poore et al. (2020)",
            "PMID_or_DOI": "10.1038/s41586-020-2095-1",
            "BioProject": "PRJNA193569",
            "cohort_description": "178 PDAC tumors paired host-microbiome",
            "PDAC_patients": "178",
            "control_patients": "0",
            "primary_tumors": "178",
            "metastatic_samples": "0",
            "treatment_status": "mixed",
            "technology": "Illumina HiSeq (WGS/RNA)",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 4",
            "suitability_status": "EXPLORATORY_ONLY",
            "inclusion_reason": "Microbiome profiles extracted from TCGA WGS/RNA-seq reads. Paired host expression available.",
            "exclusion_reason": "none",
            "official_source": "https://ftp.microbio.me/pub/cancer-microbiome/",
            "verification_status": "VERIFIED",
            "notes": "Exploratory paired analysis only."
        },
        {
            "canonical_dataset_id": "PRJNA719915",
            "accession": "PRJNA719915",
            "secondary_accession": "SRP315394",
            "repository": "NCBI BioProject",
            "publication": "Chan-Seng-Yue et al. (2020)",
            "PMID_or_DOI": "10.1038/s41591-020-0940-2",
            "BioProject": "PRJNA719915",
            "cohort_description": "62 primary tumor microbiome profiles (WGS)",
            "PDAC_patients": "62",
            "control_patients": "0",
            "primary_tumors": "62",
            "metastatic_samples": "0",
            "treatment_status": "treatment-naïve",
            "technology": "Illumina NovaSeq (WGS)",
            "scRNA_or_snRNA": "no",
            "spatial_data_available": "no",
            "processed_data_available": "yes",
            "raw_data_available": "yes",
            "patient_metadata_available": "yes",
            "malignant_cells_available": "no",
            "intended_validation_layer": "Layer 4",
            "suitability_status": "NOT_SUITABLE",
            "inclusion_reason": "none",
            "exclusion_reason": "This is the discovery microbiome cohort of the current study. Including it would result in circular validation.",
            "official_source": "https://www.ncbi.nlm.nih.gov/bioproject/PRJNA719915",
            "verification_status": "VERIFIED",
            "notes": "Discovery microbiome cohort."
        }
    ]
    
    df_inv = pd.DataFrame(datasets)[cols]
    df_inv.to_csv(ROOT / "01_metadata/external_validation_dataset_inventory.tsv", sep="\t", index=False)
    print("Generated external_validation_dataset_inventory.tsv")
    
    # Generate phase9a2_single_cell_dataset_provenance_audit.tsv
    sc_ids = ["PENG_CRA001160", "MONCADA_GSE111672", "LIN_GSE154778", "HWANG_GSE202051"]
    df_sc_audit = df_inv[df_inv["canonical_dataset_id"].isin(sc_ids)].copy()
    df_sc_audit.to_csv(ROOT / "05_results/tables/phase9a2_single_cell_dataset_provenance_audit.tsv", sep="\t", index=False)
    print("Generated phase9a2_single_cell_dataset_provenance_audit.tsv")

def generate_shortlist():
    cols = [
        "priority", "dataset_id", "accession", "validation_layer", "sample_count", "data_type",
        "primary_files", "download_size", "expected_gene_or_taxon_coverage", "negative_controls_available",
        "paired_host_microbiome", "primary_validation_endpoints", "key_limitations", "recommended_action",
        "status", "notes"
    ]
    
    data = [
        {
            "priority": "PRIORITY_1",
            "dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "validation_layer": "Layer 1 - Bulk Host",
            "sample_count": 178,
            "data_type": "Bulk RNA-seq",
            "primary_files": "gdc_download_processed_expression_matrix.tsv, clinical.tsv",
            "download_size": "~150 MB (processed)",
            "expected_gene_or_taxon_coverage": ">99% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "yes (via Poore et al. extraction)",
            "primary_validation_endpoints": "Moffitt50 axis contrast, Hallmark pathway ssGSEA, TF viper scores, WGCNA modules",
            "key_limitations": "Lack of physical normal controls (normal adjacent is rare); potential tumor-purity confounding",
            "recommended_action": "Download processed FPKM-UQ expression and clinical matrices first; calculate host scores and evaluate against clinical survival.",
            "status": "READY",
            "notes": "Gold-standard cohort for host transcriptome validation."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "GSE71729",
            "accession": "GSE71729",
            "validation_layer": "Layer 1 - Bulk Host",
            "sample_count": 145,
            "data_type": "Bulk Microarray",
            "primary_files": "GSE71729_series_matrix.txt.gz",
            "download_size": "~45 MB (processed)",
            "expected_gene_or_taxon_coverage": ">92% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Moffitt50 continuous score, singscore, PurIST, survival correlation",
            "key_limitations": "Microarray dynamic range and custom probe mapping",
            "recommended_action": "Use processed GSE71729 series matrix; map probes; apply missing-gene policy.",
            "status": "READY",
            "notes": "Moffitt discovery cohort; essential for subtyping consistency check."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "GSE62452",
            "accession": "GSE62452",
            "validation_layer": "Layer 1 - Bulk Host",
            "sample_count": 69,
            "data_type": "Bulk Microarray",
            "primary_files": "GSE62452_series_matrix.txt.gz",
            "download_size": "~18 MB (processed)",
            "expected_gene_or_taxon_coverage": ">94% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Moffitt50 continuous score, Hallmark pathway activities, survival correlation",
            "key_limitations": "Underpowered for clinical outcomes (n=69); microarray platform limitations",
            "recommended_action": "Use processed series matrix; map probes; run OLS with HC3 robust SE for tumor-vs-normal contrast.",
            "status": "READY",
            "notes": "Includes 61 adjacent normal pancreas tissues for baseline host comparisons."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "PENG_CRA001160",
            "accession": "CRA001160",
            "validation_layer": "Layer 2 - Single-Cell",
            "sample_count": 24,
            "data_type": "Single-cell RNA-seq",
            "primary_files": "CRA001160_processed_expression.h5ad",
            "download_size": "~450 MB (processed)",
            "expected_gene_or_taxon_coverage": ">95% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Malignant epithelium basal-classical cellular localization",
            "key_limitations": "High sparsity of scRNA-seq, lack of spatial coordinates",
            "recommended_action": "Download processed H5AD; perform cell-level scoring and pseudobulk by patient.",
            "status": "READY",
            "notes": "Foundational primary single-cell cohort representing Peng et al. (2019) 24 PDAC patients."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "HWANG_GSE202051",
            "accession": "GSE202051",
            "validation_layer": "Layer 3 - Spatial",
            "sample_count": 43,
            "data_type": "Spatial Transcriptomics",
            "primary_files": "GSE202051_raw_spot_counts.tar.gz, spatial_coordinates.csv",
            "download_size": "~1.2 GB (processed spots)",
            "expected_gene_or_taxon_coverage": ">90% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Spatial localization of basal-classical axis in tumor vs CAF compartments",
            "key_limitations": "Multicellular spots (10-30 cells per spot) in Visium; potential hybridization artifacts",
            "recommended_action": "Download spot expression matrices and coordinate files; perform spatial normalization.",
            "status": "READY",
            "notes": "Large spatial transcriptomics dataset for 43 patients; dual single-nucleus data available."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "GSE274103",
            "accession": "GSE274103",
            "validation_layer": "Layer 3 - Spatial",
            "sample_count": 5,
            "data_type": "Spatial Transcriptomics",
            "primary_files": "GSE274103_series_matrix.txt.gz",
            "download_size": "~150 MB",
            "expected_gene_or_taxon_coverage": ">90%",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Spatial localization of host programs",
            "key_limitations": "Small patient count (n=5)",
            "recommended_action": "Download Visium matrices and map program activities spatially.",
            "status": "READY",
            "notes": "10x Visium spatial transcriptome profiling of 5 primary PDAC patients."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "GSM3405527",
            "accession": "GSM3405527",
            "validation_layer": "Layer 3 - Spatial",
            "sample_count": 1,
            "data_type": "Spatial Transcriptomics",
            "primary_files": "GSM3405527_series_matrix.txt.gz",
            "download_size": "~15 MB",
            "expected_gene_or_taxon_coverage": ">88%",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Spatial co-localization of cell states",
            "key_limitations": "Only one patient tumor section",
            "recommended_action": "Load spatial section spot coordinates and map subtype scores.",
            "status": "READY",
            "notes": "Pioneering spatial section associated with Moncada et al. (2020)."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "PRJNA542615",
            "accession": "PRJNA542615",
            "validation_layer": "Layer 4 - Microbiome",
            "sample_count": 68,
            "data_type": "Tumor Microbiome (16S)",
            "primary_files": "SRA raw FASTQ files",
            "download_size": "~8.5 GB (raw FASTQ)",
            "expected_gene_or_taxon_coverage": "genus Ochrobactrum",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Ochrobactrum genus detection rate and survival association",
            "key_limitations": "Lack of sequenced negative controls; 16S sequencing limits resolution",
            "recommended_action": "Download raw reads; perform quality filtering; run Kraken2/Bracken; evaluate Ochrobactrum.",
            "status": "READY",
            "notes": "Must be labeled CONTAMINATION_LIMITED due to absence of controls."
        },
        {
            "priority": "PRIORITY_1",
            "dataset_id": "EGAS00001004572",
            "accession": "EGAS00001004572",
            "validation_layer": "Layer 4 - Microbiome",
            "sample_count": 120,
            "data_type": "Tumor Microbiome (16S)",
            "primary_files": "EGA raw fastq (controlled access)",
            "download_size": "~15 GB (raw FASTQ)",
            "expected_gene_or_taxon_coverage": "genus Ochrobactrum",
            "negative_controls_available": "yes",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Ochrobactrum detection vs negative controls",
            "key_limitations": "Controlled access via EGA; slow data retrieval",
            "recommended_action": "Submit access request; download raw FASTQ; process with Kraken2; compare against controls.",
            "status": "READY",
            "notes": "Gold-standard cohort for microbiome contamination validation due to extensive negative controls."
        },
        {
            "priority": "PRIORITY_2",
            "dataset_id": "LIN_GSE154778",
            "accession": "GSE154778",
            "validation_layer": "Layer 2 - Single-Cell",
            "sample_count": 10,
            "data_type": "Single-cell RNA-seq",
            "primary_files": "GSE154778_dgeMtx.csv.gz, GSE154778_RAW.tar",
            "download_size": "~120 MB",
            "expected_gene_or_taxon_coverage": ">94% of signature genes",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Malignant and stromal host feature validation",
            "key_limitations": "Small patient count (10 primary tumors), no clinical outcome",
            "recommended_action": "Download processed matrix; perform cell-level scoring and pseudobulk.",
            "status": "READY",
            "notes": "Lin et al. (2020) single-cell cohort. Primary tumors analyzed separately."
        },
        {
            "priority": "PRIORITY_2",
            "dataset_id": "MONCADA_GSE111672",
            "accession": "GSE111672",
            "validation_layer": "Layer 2 - Single-Cell",
            "sample_count": 6,
            "data_type": "Single-cell RNA-seq",
            "primary_files": "GSE111672_RAW.tar",
            "download_size": "~80 MB",
            "expected_gene_or_taxon_coverage": ">92%",
            "negative_controls_available": "no",
            "paired_host_microbiome": "no",
            "primary_validation_endpoints": "Malignant and stromal cell validation",
            "key_limitations": "Small cohort size (6 patients)",
            "recommended_action": "Download processed matrix; perform cell-level scoring and pseudobulk.",
            "status": "READY",
            "notes": "Secondary single-cell cohort associated with spatial sections."
        }
    ]
    
    df_short = pd.DataFrame(data)[cols]
    df_short.to_csv(ROOT / "05_results/tables/phase9a_external_dataset_shortlist.tsv", sep="\t", index=False)
    print("Generated phase9a_external_dataset_shortlist.tsv")

def generate_parameter_inventory():
    cols = [
        "analysis_id", "validation_layer", "dataset_id", "accession", "cohort_role", "host_or_microbiome_feature",
        "input_data", "preprocessing", "scoring_method", "covariates", "statistical_model", "replication_direction",
        "multiple_testing_family", "sample_unit", "sensitivity_analyses", "random_seed", "status", "notes"
    ]
    
    data = [
        {
            "analysis_id": "VAL_BULK_MOFFITT50_TCGA",
            "validation_layer": "Layer 1",
            "dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "Moffitt50 continuous contrast",
            "input_data": "GDC processed FPKM-UQ / counts",
            "preprocessing": "log2(x+1), row-median centered, row scaled",
            "scoring_method": "centroid-anchored reference score",
            "covariates": "tumor purity (ESTIMATE), immune/stromal score",
            "statistical_model": "Spearman rank correlation, OLS with HC3 robust SE",
            "replication_direction": "aligned (higher score = basal)",
            "multiple_testing_family": "Moffitt50 axis validation",
            "sample_unit": "patient",
            "sensitivity_analyses": "exclude low purity, no-LEMD1 contrast, singscore, PurIST",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Primary validation of continuous basal-classical axis in TCGA PAAD cohort."
        },
        {
            "analysis_id": "VAL_BULK_MOFFITT50_GSE71729",
            "validation_layer": "Layer 1",
            "dataset_id": "GSE71729",
            "accession": "GSE71729",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "Moffitt50 continuous contrast",
            "input_data": "GEO processed Agilent microarray log-ratios",
            "preprocessing": "row-median centered, row scaled",
            "scoring_method": "centroid-anchored reference score",
            "covariates": "tumor purity (ESTIMATE), immune/stromal score",
            "statistical_model": "Spearman rank correlation, OLS with HC3 robust SE",
            "replication_direction": "aligned (higher score = basal)",
            "multiple_testing_family": "Moffitt50 axis validation",
            "sample_unit": "patient",
            "sensitivity_analyses": "no-LEMD1 contrast, singscore, PurIST",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Validation of continuous basal-classical axis in the Moffitt discovery cohort."
        },
        {
            "analysis_id": "VAL_BULK_MOFFITT50_GSE62452",
            "validation_layer": "Layer 1",
            "dataset_id": "GSE62452",
            "accession": "GSE62452",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "Moffitt50 continuous contrast",
            "input_data": "GEO processed Affymetrix RMA log2 intensity",
            "preprocessing": "row-median centered, row scaled",
            "scoring_method": "centroid-anchored reference score",
            "covariates": "immune/stromal score (ESTIMATE)",
            "statistical_model": "Spearman rank correlation, OLS with HC3 robust SE",
            "replication_direction": "aligned (higher score = basal)",
            "multiple_testing_family": "Moffitt50 axis validation",
            "sample_unit": "patient",
            "sensitivity_analyses": "no-LEMD1 contrast, singscore, PurIST",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Validation of continuous basal-classical axis in Yang et al. microarray cohort."
        },
        {
            "analysis_id": "VAL_BULK_OCHRO_PATHWAY_TCGA",
            "validation_layer": "Layer 1",
            "dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "HALLMARK_PROTEIN_SECRETION, HALLMARK_SPERMATOGENESIS",
            "input_data": "GDC processed FPKM-UQ / counts",
            "preprocessing": "log2(x+1)",
            "scoring_method": "ssGSEA activity score",
            "covariates": "tumor purity (ESTIMATE), immune/stromal score",
            "statistical_model": "Spearman rank correlation, OLS with HC3 robust SE",
            "replication_direction": "negative association with Ochrobactrum (from discovery)",
            "multiple_testing_family": "Ochrobactrum host mechanism validation",
            "sample_unit": "patient",
            "sensitivity_analyses": "Moffitt50 gene exclusion from pathway matrix",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Validation of Ochrobactrum-associated Hallmark pathways in bulk TCGA cohort."
        },
        {
            "analysis_id": "VAL_BULK_OCHRO_TF_TCGA",
            "validation_layer": "Layer 1",
            "dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "34 robust TF activity candidates",
            "input_data": "GDC processed FPKM-UQ / counts",
            "preprocessing": "log2(x+1)",
            "scoring_method": "decoupleR VIPER activity score",
            "covariates": "tumor purity (ESTIMATE), immune/stromal score",
            "statistical_model": "Spearman, OLS with HC3 robust SE",
            "replication_direction": "specific locked signs per TF (as in audit)",
            "multiple_testing_family": "34 TF candidate family",
            "sample_unit": "patient",
            "sensitivity_analyses": "Moffitt50 gene exclusion, TF confidence subset (A vs B/C)",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Validation of 34 transcription factors in bulk TCGA-PAAD."
        },
        {
            "analysis_id": "VAL_BULK_WGCNA_MODULES_TCGA",
            "validation_layer": "Layer 1",
            "dataset_id": "TCGA_PAAD",
            "accession": "TCGA-PAAD",
            "cohort_role": "primary_bulk",
            "host_or_microbiome_feature": "7 robust WGCNA modules (black, blue, green, greenyellow, purple, red, tan)",
            "input_data": "GDC processed FPKM-UQ / counts",
            "preprocessing": "log2(x+1)",
            "scoring_method": "standardized mean/rank score of module genes",
            "covariates": "tumor purity (ESTIMATE), immune/stromal score",
            "statistical_model": "module eigengene-like correlation, OLS with HC3 robust SE",
            "replication_direction": "specific locked signs per module (as in audit)",
            "multiple_testing_family": "7 module family",
            "sample_unit": "patient",
            "sensitivity_analyses": "WGCNA module preservation statistics",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Validation of 7 WGCNA-derived co-expression signatures using standardized scores."
        },
        {
            "analysis_id": "VAL_SC_CELLULAR_SOURCE_PENG",
            "validation_layer": "Layer 2",
            "dataset_id": "PENG_CRA001160",
            "accession": "CRA001160",
            "cohort_role": "primary_single_cell",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "CRA001160_processed_expression.h5ad",
            "preprocessing": "LogNormalize, cell-level scaling",
            "scoring_method": "single-cell ssGSEA / AUCell / decoupleR",
            "covariates": "patient identity (random effect)",
            "statistical_model": "Pseudobulk per patient, mixed-effects regression",
            "replication_direction": "cell-compartment specific (malignant epithelium vs stroma)",
            "multiple_testing_family": "Single-cell localization family",
            "sample_unit": "patient (pseudobulk)",
            "sensitivity_analyses": "compare cell-level vs patient-pseudobulk models, verify markers",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Determine the cellular source of host features in Peng et al. scRNA-seq dataset."
        },
        {
            "analysis_id": "VAL_SC_CELLULAR_SOURCE_LIN",
            "validation_layer": "Layer 2",
            "dataset_id": "LIN_GSE154778",
            "accession": "GSE154778",
            "cohort_role": "secondary_single_cell",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE154778_dgeMtx.csv.gz",
            "preprocessing": "LogNormalize, cell-level scaling",
            "scoring_method": "single-cell ssGSEA / decoupleR",
            "covariates": "patient identity (random effect)",
            "statistical_model": "Pseudobulk per patient, mixed-effects regression",
            "replication_direction": "cell-compartment specific",
            "multiple_testing_family": "Single-cell localization family",
            "sample_unit": "patient (pseudobulk)",
            "sensitivity_analyses": "compare cell-level vs patient-pseudobulk",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Determine the cellular source of host features in Lin et al. (2020) scRNA-seq dataset."
        },
        {
            "analysis_id": "VAL_SC_CELLULAR_SOURCE_MONCADA",
            "validation_layer": "Layer 2",
            "dataset_id": "MONCADA_GSE111672",
            "accession": "GSE111672",
            "cohort_role": "exploratory_single_cell",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE111672_RAW.tar",
            "preprocessing": "LogNormalize, cell-level scaling",
            "scoring_method": "single-cell ssGSEA / decoupleR",
            "covariates": "patient identity",
            "statistical_model": "Pseudobulk per patient, mixed-effects regression",
            "replication_direction": "cell-compartment specific",
            "multiple_testing_family": "Single-cell localization family",
            "sample_unit": "patient (pseudobulk)",
            "sensitivity_analyses": "none",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Determine the cellular source of host features in Moncada et al. (2020) scRNA-seq dataset."
        },
        {
            "analysis_id": "VAL_SC_CELLULAR_SOURCE_HWANG",
            "validation_layer": "Layer 2",
            "dataset_id": "HWANG_GSE202051",
            "accession": "GSE202051",
            "cohort_role": "secondary_single_cell",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE202051_raw_spot_counts.tar.gz",
            "preprocessing": "LogNormalize, cell-level scaling",
            "scoring_method": "single-cell ssGSEA / decoupleR",
            "covariates": "patient identity, treatment status",
            "statistical_model": "Pseudobulk per patient, mixed-effects regression",
            "replication_direction": "cell-compartment specific",
            "multiple_testing_family": "Single-cell localization family",
            "sample_unit": "patient (pseudobulk)",
            "sensitivity_analyses": "separate naïve vs neoadjuvant",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Determine the cellular source of host features in Hwang et al. (2022) snRNA-seq dataset."
        },
        {
            "analysis_id": "VAL_SPATIAL_CO_LOCAL_HWANG",
            "validation_layer": "Layer 3",
            "dataset_id": "HWANG_GSE202051",
            "accession": "GSE202051",
            "cohort_role": "primary_spatial",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE202051_raw_spot_counts.tar.gz, spatial_coordinates.csv",
            "preprocessing": "SCTransform / log-normalize, spatial registration",
            "scoring_method": "spot-level pathway / TF activity scoring",
            "covariates": "tissue compartment (malignant vs CAF-rich vs immune-rich)",
            "statistical_model": "spatial autocorrelation-aware model, spot-level ANOVA with patient block",
            "replication_direction": "spatially localized (proximity to tumor epithelium vs stroma)",
            "multiple_testing_family": "Spatial localization family",
            "sample_unit": "spot (within-patient) and patient (aggregated)",
            "sensitivity_analyses": "adjust for local cell-composition estimates, multiple sections",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Assess spatial localization and co-occurrence of host programs in Hwang et al. spatial sections."
        },
        {
            "analysis_id": "VAL_SPATIAL_CO_LOCAL_WANG",
            "validation_layer": "Layer 3",
            "dataset_id": "GSE274103",
            "accession": "GSE274103",
            "cohort_role": "primary_spatial",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE274103_series_matrix.txt.gz",
            "preprocessing": "SCTransform / log-normalize, spatial registration",
            "scoring_method": "spot-level pathway / TF activity scoring",
            "covariates": "tissue compartment",
            "statistical_model": "spatial autocorrelation-aware model, spot-level ANOVA with patient block",
            "replication_direction": "spatially localized",
            "multiple_testing_family": "Spatial localization family",
            "sample_unit": "spot (within-patient) and patient (aggregated)",
            "sensitivity_analyses": "none",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Assess spatial localization in Wang et al. 2024 spatial sections."
        },
        {
            "analysis_id": "VAL_SPATIAL_CO_LOCAL_MONCADA",
            "validation_layer": "Layer 3",
            "dataset_id": "MONCADA_GSE111672",
            "accession": "GSE111672",
            "cohort_role": "primary_spatial",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSM3405527 / GSE111672",
            "preprocessing": "SCTransform / log-normalize, spatial registration",
            "scoring_method": "spot-level pathway / TF activity scoring",
            "covariates": "tissue compartment",
            "statistical_model": "spatial autocorrelation-aware model, spot-level ANOVA with patient block",
            "replication_direction": "spatially localized",
            "multiple_testing_family": "Spatial localization family",
            "sample_unit": "spot (within-patient) and patient (aggregated)",
            "sensitivity_analyses": "none",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Assess spatial localization in Moncada et al. 2020 spatial sections."
        },
        {
            "analysis_id": "VAL_SPATIAL_CO_LOCAL_ZHANG",
            "validation_layer": "Layer 3",
            "dataset_id": "GSE272362",
            "accession": "GSE272362",
            "cohort_role": "secondary_spatial",
            "host_or_microbiome_feature": "Moffitt50, 2 pathways, 34 TFs, 7 modules",
            "input_data": "GSE272362 Visium counts",
            "preprocessing": "SCTransform",
            "scoring_method": "spot-level scoring",
            "covariates": "compartment, tissue site",
            "statistical_model": "spatial regression model",
            "replication_direction": "spatially localized",
            "multiple_testing_family": "Spatial localization family",
            "sample_unit": "spot",
            "sensitivity_analyses": "primary vs metastatic contrast",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Assess spatial localization in Zhang et al. 2024 spatial sections."
        },
        {
            "analysis_id": "VAL_MICRO_OCHRO_DETECTION_RIQUELME",
            "validation_layer": "Layer 4",
            "dataset_id": "PRJNA542615",
            "accession": "PRJNA542615",
            "cohort_role": "primary_microbiome",
            "host_or_microbiome_feature": "Ochrobactrum abundance and presence",
            "input_data": "SRA raw FASTQ files",
            "preprocessing": "fastp QC, host-read depletion (Bowtie2 to GRCh38), taxonomic profiling",
            "scoring_method": "Kraken2/Bracken taxonomic abundance, CLR transformed",
            "covariates": "sequencing batch, extraction run",
            "statistical_model": "prevalence and relative abundance statistics, low-biomass filter",
            "replication_direction": "Ochrobactrum detected in independent tumor tissues",
            "multiple_testing_family": "Microbiome validation family",
            "sample_unit": "patient",
            "sensitivity_analyses": "alternative taxonomic profiler (MetaPhlAn4), low-biomass filter stress test",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Verify Ochrobactrum presence and abundance in Riquelme et al. 16S cohort."
        },
        {
            "analysis_id": "VAL_PAIRED_HOST_MICRO_TCGA",
            "validation_layer": "Layer 1 + Layer 4",
            "dataset_id": "TCGA_PAAD_microbiome",
            "accession": "TCGA-PAAD",
            "cohort_role": "exploratory_paired",
            "host_or_microbiome_feature": "host features ~ Ochrobactrum abundance",
            "input_data": "TCGA RNA-seq and paired Knight Lab microbiome CLR matrix",
            "preprocessing": "standard CLR / rCLR for microbiome, log2(x+1) for host",
            "scoring_method": "OLS regression with host feature as dependent variable",
            "covariates": "ESTIMATE tumor purity, immune/stromal score, sequencing center",
            "statistical_model": "OLS with HC3 robust standard errors",
            "replication_direction": "aligned with discovery host-microbiome coefficients",
            "multiple_testing_family": "paired association family",
            "sample_unit": "patient",
            "sensitivity_analyses": "rCLR direction check, exclusion of high-leverage samples",
            "random_seed": "2026",
            "status": "LOCKED",
            "notes": "Exploratory evaluation of paired host features and Ochrobactrum in TCGA."
        }
    ]
    
    df_param = pd.DataFrame(data)[cols]
    df_param.to_csv(ROOT / "01_metadata/external_validation_parameter_inventory.tsv", sep="\t", index=False)
    print("Generated external_validation_parameter_inventory.tsv")

def generate_authoritative_cohort_set():
    cols = [
        "canonical_dataset_id", "accession", "publication", "PDAC_patients", "analysis_role",
        "suitability_status", "included_in_phase9b2", "processed_files_to_download", "estimated_size",
        "treatment_handling", "patient_unit", "limitations", "notes"
    ]
    
    data = [
        {
            "canonical_dataset_id": "PENG_CRA001160",
            "accession": "CRA001160",
            "publication": "Peng et al. (2019)",
            "PDAC_patients": "24",
            "analysis_role": "Layer 2 primary single-cell cellular source validation",
            "suitability_status": "PRIORITY_1",
            "included_in_phase9b2": "yes",
            "processed_files_to_download": "CRA001160_processed_expression.h5ad",
            "estimated_size": "~450 MB",
            "treatment_handling": "Treatment-naïve (resectable primary tumors)",
            "patient_unit": "Patient-level pseudobulk (n=24)",
            "limitations": "Sparsity of single-cell RNA-seq, lack of spatial coordinates",
            "notes": "Authoritative Peng et al. 2019 dataset. Accession CRA001160; BioProject PRJCA001063. Formally corrected from GSE111672."
        },
        {
            "canonical_dataset_id": "LIN_GSE154778",
            "accession": "GSE154778",
            "publication": "Lin et al. (2020)",
            "PDAC_patients": "10",
            "analysis_role": "Layer 2 secondary single-cell cellular source validation",
            "suitability_status": "PRIORITY_2",
            "included_in_phase9b2": "yes",
            "processed_files_to_download": "GSE154778_dgeMtx.csv.gz, GSE154778_RAW.tar",
            "estimated_size": "~120 MB",
            "treatment_handling": "Treatment-naïve (10 primary tumors, 6 metastatic biopsies analyzed separately)",
            "patient_unit": "Patient-level pseudobulk (n=10 primary tumors)",
            "limitations": "Small patient size (10 primary tumors), no clinical survival outcomes",
            "notes": "Confirmed as public and containing malignant cells. NOT controlled-access or CD45+ sorted (unlike Steele et al. 2020)."
        },
        {
            "canonical_dataset_id": "MONCADA_GSE111672",
            "accession": "GSE111672",
            "publication": "Moncada et al. (2020)",
            "PDAC_patients": "6",
            "analysis_role": "Layer 3 spatial validation and Layer 2 exploratory single-cell cohort",
            "suitability_status": "PRIORITY_1 (spatial) / PRIORITY_2 (single-cell)",
            "included_in_phase9b2": "yes",
            "processed_files_to_download": "GSM3405527 microarray spatial / GSE111672_RAW.tar",
            "estimated_size": "~80 MB",
            "treatment_handling": "Treatment-naïve (primary tumors)",
            "patient_unit": "Spot-level coordinates (spatial) / patient pseudobulk (single-cell, n=6)",
            "limitations": "Small cohort size (6 patients)",
            "notes": "Authoritative Moncada et al. 2020 dataset. Formally corrected from Peng 2019."
        },
        {
            "canonical_dataset_id": "HWANG_GSE202051",
            "accession": "GSE202051",
            "publication": "Hwang et al. (2022)",
            "PDAC_patients": "43",
            "analysis_role": "Layer 3 primary spatial validation and Layer 2 secondary/treatment-sensitivity cellular source evaluation",
            "suitability_status": "PRIORITY_1 (spatial) / PRIORITY_2 (single-cell)",
            "included_in_phase9b2": "yes",
            "processed_files_to_download": "GSE202051_raw_spot_counts.tar.gz, spatial_coordinates.csv",
            "estimated_size": "~1.2 GB",
            "treatment_handling": "Analyze treatment-naïve (n=21) and neoadjuvant-treated (n=22) samples separately to evaluate treatment sensitivity",
            "patient_unit": "Spot-level coordinates (spatial) / patient pseudobulk (single-nucleus, n=43)",
            "limitations": "snRNA-seq capture differences; neoadjuvant treatment confounding",
            "notes": "Large dual-modality Visium and snRNA-seq dataset."
        }
    ]
    
    df_auth = pd.DataFrame(data)[cols]
    df_auth.to_csv(ROOT / "05_results/tables/phase9a2_phase9b2_authoritative_cohort_set.tsv", sep="\t", index=False)
    print("Generated phase9a2_phase9b2_authoritative_cohort_set.tsv")

def main():
    generate_inventory()
    generate_shortlist()
    generate_parameter_inventory()
    generate_authoritative_cohort_set()

if __name__ == "__main__":
    main()
