package	source	version	library_path	installed
renv	CRAN	1.2.3	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
BiocManager	CRAN	1.30.27	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
WGCNA	CRAN	1.74	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
msigdbr	CRAN	26.1.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
matrixStats	CRAN	1.5.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
dynamicTreeCut	CRAN	1.63-1	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
fastcluster	CRAN	1.3.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
tidyverse	CRAN	2.0.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
data.table	CRAN	1.18.4	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
sandwich	CRAN	3.1-1	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
lmtest	CRAN	0.9-40	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
decoupleR	Bioconductor	2.16.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
progeny	Bioconductor	1.32.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
dorothea	Bioconductor	1.22.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
viper	Bioconductor	1.44.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
GSVA	Bioconductor	2.4.9	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
limma	Bioconductor	3.66.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
edgeR	Bioconductor	4.8.2	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
clusterProfiler	Bioconductor	4.18.4	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
ReactomePA	Bioconductor	1.54.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
fgsea	Bioconductor	1.36.2	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
BiocParallel	Bioconductor	1.44.0	~/thesis/PDAC/renv/library/macos/R-4.5/aarch64-apple-darwin20	TRUE
